### ISSUE TITLE
Main Navigation > Hamburger Menu Animation

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#34]
the Hamburger menu Icon should mimic the animation in this codepen (menu #2) 
https://codepen.io/KPCodes/pen/Ypwrdx
![image](https://user-images.githubusercontent.com/8764348/72361055-d4cb4980-36be-11ea-9e38-e00a4e805304.png)

**Comment by SCarrero** [comment]
Until I have time to write the javascript that is necessary to turn our current 3 buttons into one, and track all the statuses of what is open and needing to be closed at each step, it will stay as is.  
I'm trying to focus on css and html right now, so that the requirements for Ad team are complete.  So, just letting you know that this will probably not happen until after transformation and the council projects are complete.

**Comment by jpyo** [comment]
@SCarrero no problem, just adding it to keep track of it. Im going to add one for the menu navigation also. But same thing, just trying to keep a log of it.

**Comment by jpyo** [comment]
@SCarrero also for reference, this is the website i pulled up last week that has a similar functionality if you are able to gather anything from the way they are achieving it https://www.dormify.com/

**Comment by SCarrero** [comment]
Which method do you prefer? The dormify site has dashes connecting the 3 lines and curling as they rotrate into an X, while the codepen version just has the top and bottom sliding into an X position.

**Comment by jpyo** [comment]
@SCarrero like the codepen example. It's also animated the way we'd like in the Principle prototype

**Comment by SCarrero** [comment]
please review
