### ISSUE TITLE
Main Navigation > Open/Close Animation

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#37]
The menu background should grow out from the background of the search/menu bar, not scale entirely in to/out of the corner.

In the prototype the order of animation is:
- main menu background grows from search/menu bar and changes background color to grey
- the search icon seen in the top right corner fades out
- the tiles and search bar animated in on top of the grey background

![image](https://user-images.githubusercontent.com/8764348/72367699-a489a800-36ca-11ea-91c0-dbb234dc115f.png)

**Comment by SCarrero** [comment]
are you animating that layer by scaling it  up and down (instead of sliding in and out at full size, like I've got it doing)?

**Comment by jpyo** [comment]
@SCarrero yea it is scaling to size not sliding

**Comment by SCarrero** [comment]
In the principle animation you sent me, the 6 tiles slide down and become opaque while the white box expands and turns gray, instead of scaling in with the container.  (in fact, the tiles slide down and become visible before the box scales in behind them,  so it's like they aren't even contained by the box with the gray background.  Not sure if I can duplicate what I'm viewing in the Principle viewer -- the gray box would need to be an entirely different container than the one with the tiles in order for for the tiles to slide in before the container box has expanded full width -- and I'd just have to guess at height on the gray background, since it really wouldn't have anything inside of it.  
I prefer the idea you show above of everything just scaling in, but it's not what you sent me from Principle.

**Comment by jpyo** [comment]
@SCarrero we do want to stick to the Principle prototype as much as we can. 

Alternatively, would it make it any easier if we removed the scaling and fading all together and did something with more of a "reveal" action? Check this example out https://melriver.com/ Once the page loads, click the menu button on the top right to see how content is pushed down and a menu is revealed underneath.

**Comment by SCarrero** [comment]
There is no scaling in the principle file I have.  The icon tiles start at full size and just shift downward slightly while the gray background eventually grows behind them -- but they are visible before the gray background grows.  Is there a way to take a screen shot on a Mac? I could try to show you what I'm seeing.
That site slides down to reveal a navigation pane below the content -- I thought you wanted the navigation to come in on top and overlay the content.

**Comment by SCarrero** [comment]
My problem in the animation you describe in the first comment on this issue is not at all what I see in the principle file.

**Comment by SCarrero** [comment]
initial nav is now exposed by content area sliding down.

**Comment by jpyo** [comment]
@SCarrero looking good, a couple things i noticed:

1. There is a grey side bar showing on the right when the browser is larger than 1440px.
2. Is there a way to put an ease-transition on the blurring/dark overlay of the non-menu area? It currently just pops into the blurred state which is a little jarring.

**Comment by SCarrero** [comment]
I've slowed down the blur with a transition.
That grey scrollbar should only exist when the window isn't tall enough to contain the tallest nav height --  It shouldn't be visible if your window is over 657px tall.  I just modified it so it also shouldn't show if your window is at least 1024px -- since users with that width can choose to make their windows taller than 657 if they want.

**Comment by jpyo** [comment]
@SCarrero that's better! sidebar issue is gone for me too. 

can you make the grey overlay also have the same ease transition? it's still popping on and off.

**Comment by SCarrero** [comment]
not sure what you mean by the gray overlap ? Do you mean the background of light gray for the hamburger tile nav, that is behind the bottommost layer?   It's there all the time under the content, and you don't see it until the content slides off of it -- so there's transition occurring on that layer at all -- it's there all along, you just don't see it until the top layer slides down to expose it.  This was based on the desire to have content slide down to expose nav similar to https://melriver.com/

**Comment by jpyo** [comment]
@SCarrero overlaY not overlaP. Im talking about the tinting that happens over the bottom content when you expose the menu. It just turns on and off but i would like that to have a transition on it

**Comment by jpyo** [comment]
@SCarrero the tinting on this area:
![image](https://user-images.githubusercontent.com/8764348/75718965-e504ab80-5ca1-11ea-8ca1-0cb6602566b6.png)

**Comment by SCarrero** [comment]
Ah!!!!!   so totally different than the gray I was thinking of. Yes, that is doable.
Wasn't sure if the graying effect was even still necessary since we're preventing users from scrolling to the content.
Please review again -- I've added a transition.

**Comment by jpyo** [comment]
@SCarrero awesome, closing this now!
