### ISSUE TITLE
Detail Page > Next/Prev Arrow Hover Animations

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#40]
can we try something like this for the arrow hovers on the next/prev button on the bottom of the detail pages?

![arrow-hover](https://user-images.githubusercontent.com/8764348/72376125-72347680-36db-11ea-95fd-f28e4d42db80.gif)

**Comment by SCarrero** [comment]
that's trippy.   Like it slides off to the right and reappears from the left.  I think that would only work for hover, not for focus. 
The words are also clickable -- the entire box is clickable, with just the left edge going backwards, if the page has a prev link.

**Comment by jpyo** [comment]
@SCarrero it's kind of like what is happening in the purple section of these demos: https://tympanus.net/Development/CreativeButtons/

I think the arrows need to be the focus area though, atleast for when there are options to go back or forth. I think it's confusing that clicking anywhere else besides the back arrow triggers it to go forward

**Comment by SCarrero** [comment]
I have a similar page I work on in my spare time for things like button animations:
http://www.freddiemac.com/special/design/links.html

I guess I'm weird -- for years we used icons as visual markers and decorations, but they were rarely clickable, so I'm not in the habit of clicking icons.  Just big targets.  I can remove the link from the center box if you like though. so it's not clickable.

**Comment by SCarrero** [comment]
Also, the green bar is currently set up so that when there is no forward page, the entire green bar goes back.

**Comment by jpyo** [comment]
> Also, the green bar is currently set up so that when there is no forward page, the entire green bar goes back.
@SCarrero that is fine.

How about for the ones with both arrows we split the focus area in half? so left half triggers the left arrow animation and right half trigger the right arrow animation. And clicking either side is also the hotspot?

**Comment by SCarrero** [comment]
Wouldn't that be weird if the user clicked on the "next panel" text, and wound up going backwards if their click was on the left half of the word?  
Right now it's made up of 3 blocks: 
- left block: if there is a prev page, contains back arrow and links to prev page, otherwise if there is only a next page, it links forward, but with no image.
- large center block: if there is a next step, it contains text for that item and links forward, otherwise if there is only a prev step, it contains the text for the prev item and links backwards..
- right block: if there is a next page, contains forward arrow and links to next page, otherwise if there is only a prev page, it links backward, but with no image.
 
Far easier to remove the link from the middle block and have it not be clickable, than redesigning it to be 2 block links with the text overlaid in the center on top of them.

**Comment by jpyo** [comment]
I think thats why it's important to have that arrow animation trigger on either half of the button so you know which direction it is going in. let me try prototyping it

**Comment by SCarrero** [comment]
please review.
