### ISSUE TITLE
Tools & Resources > (mobile) Content Alignment

### ISSUE THREAD

**Issue by jpyo** [SCarrero/home#54]
Left-align copy to the same line as the heading, and center the Illustrations horizontally on mobile

![image](https://user-images.githubusercontent.com/8764348/72830939-d1503900-3c4f-11ea-8eb9-cfba86845bed.png)

**Comment by SCarrero** [comment]
At the moment, those cards are sized to match the blog card layout at small, where the cards center once there's over 380px width for them (to prevent the photo from getting stretched beyond 100% -- they crop those images pretty small).  
Since these won' have photos, I can set these so the text goes edge to edge instead of matching the blog card layout.
![image](https://user-images.githubusercontent.com/20446484/72932609-177bca00-3d2e-11ea-9292-a00ef4720d4d.png)

**Comment by SCarrero** [comment]
please review.

**Comment by SCarrero** [comment]
Closing. Cinzia reversed this decision and they are back to left aligned.
